### PR TITLE
Added getByName method to Element.java file and to WebElement.java file

### PR DESCRIPTION
**Pull request by brian-menzies**
Added a getByName method to Element.java file and WebElement.java file. The getByName method transforms a @FindBy Element Declaration into a definition able to be handled by driver.findElement() or driver.findElements(). This will work in Interfaces and allow the user to return elements from within a method within an interface.

### CODE REVIEW

**Comment by JustinPhlegar** [comment]
Slight typo in example above, both FindBy and FindBys are valid for List<?>

**Comment by brian-menzies** [comment]
I continued to receive NullPointerExceptions when attempting to use only a FindBy reference from within an interface extension. As such, I saw that using a driver.FindElement(By. ...) was able to successfully find and return the element I wanted, so I didn't want to continuously rewrite all the find types and their values, so I made this method so that all would be required in the event of a rewrite within the interface would be to "rename" it within the getByName method and change the corresponding @FindBy declaration.

**Comment by JustinPhlegar** [comment]
Can you share a code example and stack trace of the NPE? It might be a bug. We have a unit test for using findBy as a List using custom interfaces. https://github.com/Orasi/Chameleon/blob/stage/src/test/java/com/orasi/web/webelements/TestElementInternalHandlers.java#L68-L71.

I would rather fix a bug than have a work around for a bug.

**Comment by brian-menzies** [comment]
Sure thing Justin. I'll try and provide that early tomorrow.

**Comment by brian-menzies** [comment]
Created a New Pull Request that contains the Code examples of FindBy within an interface returning Null. Unfortunately there wasn't much in the way of error information, but I added what I could.

NPE error was:
Closing the Browser
java.lang.NullPointerException
at Steps.CommonSteps.iNavigateToARandomSeries(CommonSteps.java:114)
  at ✽.And I Navigate to a Random Series(C:/Work/JavaTesting/ibmcvCucumber/src/test/java/Tests/SearchTests.feature:82)

**Comment by JustinPhlegar** [comment]
This is not needed in Chameleon as use cases provided are already covered with existing functionality. Closing this PR.

**Pull request closed without merging**
